package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func renderRules(c config, lan, wan interfaceState) (string, string, error) {
	if err := c.validateNetworks(lan, wan); err != nil {
		return "", "", err
	}
	var nat, forward strings.Builder
	nat.WriteString("# Generated by lan-service-gateway; do not edit.\n")
	forward.WriteString("# Generated by lan-service-gateway; do not edit.\n")
	add := func(ingress, routerIP, targetIP, proto string, externalPort, targetPort uint16) {
		fmt.Fprintf(&nat, "iifname %q ip daddr %s %s dport %d dnat ip to %s:%d\n", ingress, routerIP, proto, externalPort, targetIP, targetPort)
		fmt.Fprintf(&forward, "iifname %q ip daddr %s %s dport %d ct status dnat accept\n", ingress, targetIP, proto, targetPort)
	}
	for _, m := range c.localSend {
		add(wan.device, wan.ip.String(), m.ip.String(), "tcp", m.proxyPort, m.port)
	}
	if c.sunshine != nil {
		for _, p := range c.sunshine.tcpPorts {
			add(wan.device, wan.ip.String(), c.sunshine.ip.String(), "tcp", p, p)
		}
		for _, p := range c.sunshine.udpPorts {
			add(wan.device, wan.ip.String(), c.sunshine.ip.String(), "udp", p, p)
		}
	}
	return nat.String(), forward.String(), nil
}

func writeRules(dir, applyPath, nat, forward string) error {
	var chains strings.Builder
	chains.WriteString("chain lsg_dstnat {\n")
	chains.WriteString(nat)
	chains.WriteString("}\nchain lsg_forward {\n")
	chains.WriteString(forward)
	chains.WriteString("}\n")
	var apply strings.Builder
	apply.WriteString("flush chain inet fw4 lsg_dstnat\n")
	for _, line := range strings.Split(nat, "\n") {
		if line != "" && !strings.HasPrefix(line, "#") {
			fmt.Fprintf(&apply, "add rule inet fw4 lsg_dstnat %s\n", line)
		}
	}
	apply.WriteString("flush chain inet fw4 lsg_forward\n")
	for _, line := range strings.Split(forward, "\n") {
		if line != "" && !strings.HasPrefix(line, "#") {
			fmt.Fprintf(&apply, "add rule inet fw4 lsg_forward %s\n", line)
		}
	}
	files := []struct{ path, body string }{
		{filepath.Join(dir, "chain-pre", "dstnat", "90-lan-service-gateway.nft"), "jump lsg_dstnat comment \"lan-service-gateway\"\n"},
		{filepath.Join(dir, "chain-pre", "forward", "90-lan-service-gateway.nft"), "jump lsg_forward comment \"lan-service-gateway\"\n"},
		{filepath.Join(dir, "table-post", "90-lan-service-gateway.nft"), chains.String()},
		{applyPath, apply.String()},
	}
	for _, file := range files {
		if err := os.MkdirAll(filepath.Dir(file.path), 0755); err != nil {
			return err
		}
		tmp, err := os.CreateTemp(filepath.Dir(file.path), ".lsg-*")
		if err != nil {
			return err
		}
		defer os.Remove(tmp.Name())
		if _, err = tmp.WriteString(file.body); err != nil {
			tmp.Close()
			return err
		}
		if err = tmp.Close(); err != nil {
			return err
		}
		if err = os.Rename(tmp.Name(), file.path); err != nil {
			return err
		}
	}
	return nil
}
